### ISSUE TITLE
Adding direct downloads ranking, and possibility to compare different packages

### ISSUE THREAD

**Issue by AndreaPi** [metacran/metacranweb#100]
I think a useful addition to the [METACRAN](https://www.r-pkg.org/) site would a ranking of packages by direct downloads. **Most downloaded** seems to be based on _total_ downloads, i.e., including dependency downloads. No surprise `Rcpp` comes first - it's also one of the most depended upon CRAN packages.

Also, it would be nice to offer the possibility of comparing two or three packages one against the other - i.e., add a form where I select, say, `skimr` and `summarytools`, and get a table which compares them by number of direct downloads, downloads this month, stars on GitHub, etc.

**Comment by gaborcsardi** [comment]
We don't know which download is direct and which one is not.

As for the comparison, the UI for that is a bit hard to write, I think  it is simpler to write an R package for it.

**Comment by AndreaPi** [comment]
@gaborcsardi thanks for the reply. 

Concerning the direct/dependent downloads, there must be a way to find out, though I have no idea how difficult it is. If you look at https://www.rdocumentation.org/packages/glue/versions/1.2.0 for example and hover over the "i" next to the number of monthly downloads, you see the following tooltip:
![image](https://user-images.githubusercontent.com/8233615/39087018-37333eec-459a-11e8-86a2-8d06a6619017.png)
As a matter of fact, the API of RDocumentation allows splitting the downloads in direct/indirect:
https://www.rdocumentation.org/docs/#api-Package-Get_splitted_package_downloads
Maybe you could interrogate it?

Of course it may be very difficult - I have no idea how they do it.

Concerning the UI, no worries, if that's too complicated please just forget about it.

**Comment by gaborcsardi** [comment]
They have a statistical model for the direct and indirect numbers, but in my experience it is not very good, the numbers do not seem plausible at all. 

Even their totals do not add up to the correct numbers.

**Comment by AndreaPi** [comment]
I didn't notice that! Then it's not a good idea.
