### ISSUE TITLE
Badge shows unpublished but package is on CRAN

### ISSUE THREAD

**Issue by FilipeamTeixeira** [metacran/metacranweb#101]
This package https://github.com/ropensci/skynet, shows as unpublished, but you can find it on CRAN under version 1.2.2.

Not sure what the reason is.

**Comment by LiNk-NY** [comment]
I'm getting the same issue: 
https://www.r-pkg.org/badges/version/BiocManager
https://cran.r-project.org/package=BiocManager

**Comment by gaborcsardi** [comment]
Should be ok now.
