### ISSUE TITLE
CRAN Version Badge Error: error on line 1 at column 2: StartTag: invalid element name

### ISSUE THREAD

**Issue by jessecambon** [metacran/metacranweb#108]
I am using the R CRAN version badge for my package and it recently stopped working. Here is the link: https://www.r-pkg.org/badges/version/tidygeocoder. It currently is showing this error:
```
This page contains the following errors:
error on line 1 at column 2: StartTag: invalid element name
```
Other packages I looked at do not seem to have this issue. Any ideas what is causing this? Here is my package's CRAN page for reference: https://CRAN.R-project.org/package=tidygeocoder

**Comment by gaborcsardi** [comment]
Thanks for letting me know, fixed now. For some reason cloudflare cached a broken file for you, I have no clue why.

**Comment by gavinsimpson** [comment]
I'm seeing the same thing for https://www.r-pkg.org/badges/version/cocorresp currently.

**Comment by gaborcsardi** [comment]
@gavinsimpson Thanks, fixed!
