### ISSUE TITLE
Certificate CA error?

### ISSUE THREAD

**Issue by ewenharrison** [metacran/metacranweb#115]
Hi,
Is there a certificate issue with `crandb.r-pkg.org`? Been doing this for a while now with me. 
Many thanks. 
Ewen

```
> httr::RETRY("GET", "https://crandb.r-pkg.org/finalfit/all", quiet = FALSE)
Error in curl::curl_fetch_memory(url, handle = handle): server certificate verification failed. CAfile: none CRLfile: none
Request failed [ERROR]. Retrying in 1.3 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): server certificate verification failed. CAfile: none CRLfile: none
Request failed [ERROR]. Retrying in 3.7 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  server certificate verification failed. CAfile: none CRLfile: none
```

**Comment by gaborcsardi** [comment]
No, the certificate is fine, the issue is with your client. Probably an older macOS or Linux?

**Comment by ewenharrison** [comment]
> No, the certificate is fine, the issue is with your client. Probably an older macOS or Linux?

Many thanks. It is new Ubuntu 20.04 will all certificates appropriately installed. I'm following up via the above link. 
Thanks again.
