### ISSUE TITLE
Could you remove the irtplay package from "https://github.com/cran/irtplay"?

### ISSUE THREAD

**Issue by hwangQ** [metacran/metacranweb#116]
Dear maintainer,

Hello. This is Hwanggyu Lim. I am an author of the irtplay R package” uploaded in R CRAN.
Could you please remove the irtplay package from "https://github.com/cran/irtplay". It is becasue some parts of the code are related with the intellection property violation issue. I already contacted R-CRAN mainatiners to ask them to remove the package.   
I am really sorry for causing this issue

Best,
Hwanggyu

**Comment by gaborcsardi** [comment]
Does this apply to the latest version only or to all versions? 

I'll be happy to remove it, once CRAN has removed it as well. I cannot remove it before, because this being a mirror it will be re-created again.

**Comment by hwangQ** [comment]
Yes, please remove all versions. I've already requested CRAN to remove the package as well. Thanks!

**Comment by gaborcsardi** [comment]
OK, I removed the repo from github.com/cran/ and also the package from metacran. It is still in the cache on metacran. I'll check that it is completely gone in a days or so.

**Comment by hwangQ** [comment]
Thank you so much for your help. Have a great day!

Best,
Hwanggyu
