### ISSUE TITLE
Error in Seqinr

### ISSUE THREAD

**Issue by tourajrahimi** [metacran/metacranweb#118]
Hi Dear
I updated my seqinr to 4.2-23 a couple of days ago and I got this Error. 
I use Rstudio version 2022.12.0 Build 353 and R version R4.2.2 on Windows 10.
> choosebank()
Error in if (res[1] != "0") { : argument is of length zero

I checked the seqinr 's manual and found that macOS has had a similar problem before.
but the tips weren't helpful to me. How can I fix this problem, Please could you advise me.
Many Thanks

**Comment by gaborcsardi** [comment]
This project has nothing to do with that package, see `BugReports` and `Maintainer` in `DESCRIPTION`: https://cran.rstudio.com/web/packages/seqinr/
