### ISSUE TITLE
CRAN version badge fails for some packages

### ISSUE THREAD

**Issue by klmr** [metacran/metacranweb#121]
Compare:

```
$ curl -ILs https://www.r-pkg.org/badges/version/Rcpp  | head -1
HTTP/2 200

$ curl -ILs https://www.r-pkg.org/badges/version/box | head -1
HTTP/2 404
```

(Obviously both packages are on CRAN, not archived, etc.)

**Comment by gaborcsardi** [comment]
Looks good now.

**Comment by klmr** [comment]
Ah, indeed. I did check repeatedly. And for an intermittent availability issue it’s a bit odd that some packages work while others don’t, isn’t it?

**Comment by gaborcsardi** [comment]
Some were in the cache, I guess.
