### ISSUE TITLE
Rendering Quarto reveal.js only "Not Published" badges

### ISSUE THREAD

**Issue by adamhsparks** [metacran/metacranweb#122]
I'm attempting to use badges in a reveal.js slide deck in Quarto but I only ever get the "Not Published" image in the knitted deck, _e.g._, using <https://www.r-pkg.org/badges/version/agricolae> as the image source only returns the bronze "Not Published" badge, not the green version number that this link points to.

For most of the packages in the slide deck that I'm talking about, it's true, but for this one, I'd like to be able to indicate it's on CRAN.

**Comment by gaborcsardi** [comment]
That badge looks good to me. Does it look ok to you if you click on it here?

**Comment by adamhsparks** [comment]
Sorry, I wasn't clear. It looks ok here and if I click on it from the presentation. However, IN the presentation it's the incorrect badge that's shown no matter what I do. Clicking on it takes me to the proper green one but the reveal.js presentation HTML displays the "Not on CRAN" for any/all packages when rendered.

**Comment by gaborcsardi** [comment]
That does not seem like a problem with the server. It is also pretty hard to guess what is wrong without seeing the actual presentation.

**Comment by gaborcsardi** [comment]
The link is incorrect here: https://github.com/adamhsparks/test_qmd/blob/main/test_qmd.html#L351

**Comment by gaborcsardi** [comment]
See https://github.com/quarto-dev/quarto-cli/issues/6092
