### ISSUE TITLE
Has https://r-pkg.org/ and/or https://crandb.r-pkg.org/ stopped updating?

### ISSUE THREAD

**Issue by remlapmot** [metacran/metacranweb#128]
I notice the most recent update on <https://r-pkg.org/recent> seems to be from 3 days ago, and I think this is usually up to date.

<img width="1236" alt="Screenshot 2024-06-14 at 21 32 32" src="https://github.com/metacran/metacranweb/assets/3777473/a493781c-c26d-44b3-899e-2c3cac320237">

**Comment by gaborcsardi** [comment]
Thanks, I think updates are working now.

**Comment by remlapmot** [comment]
Brill, thanks
