### ISSUE TITLE
Searches Return Only One Page of Ten Results

### ISSUE THREAD

**Issue by jpoconnor1961** [metacran/metacranweb#129]
Key word searches for package types on this site returns only one page of results consisting of the first 10 packages listed with their descriptions.  The same page of results also shows at the top of the page that over 1000 packages were found, and at the bottom of the results page are a row of boxes numbered 1 to 10 indicating pages of additional results from the search.  However, clicking on any one of the 10 pages returns only the original page of the first 10 packages that were already listed, and no other additional results.  Furthermore, when the 10th page is clicked, the >> icon, for advancing to the next page of results, disappears!  

All the problems above are reproduceable regardless of key words searched, where in the METACRAN site the search is initiated, which of two browsers I use, Google Chrome or MS Edge, and which of two OS I use, Windows 10 or Windows 11 -- I get the exact same search limitations described above regardless of combination of conditions, i.e., tested all possibilities on Windows 10 & 11 with Google Chrome & MS Edge.

**Comment by gaborcsardi** [comment]
Thanks, this should be fixed, but unfortunately the results are not great, I just noticed that the download counts are not updated properly, so the weighting is very off. :(
