### ISSUE TITLE
Fix badges in READMEs

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/metacranweb#41]
marky adds a 'badge' class to some of them. Bootstrap hides them by default, and it also styles them.

**Comment by eddelbuettel** [comment]
Oh I see. Anything we (as `README.md` authors) should do differently?

**Comment by gaborcsardi** [comment]
Not much. One thing would be to store images (and other external files) in `inst` and include them in the built package. Then have relative links to them from the README. Then they are shown properly on Github, and I can also link them from http://github.com/cran/ I'll make an example in one of my packages.

But badges are special, of course, and I might treat them (even more) specially later. E.g. I want to have badges for CRAN checks, they will make more sense on metacran than Travis badges that are for the latest dev build.

**Comment by gaborcsardi** [comment]
OK, all fixed now, all READMEs rebuilt.

**Comment by eddelbuettel** [comment]
Rocking!   Leaving a [link here in case I forget the URL](http://www.r-pkg.org/pkg/Rcpp) again ;-)
