### ISSUE TITLE
Page not found errors with package or search.

### ISSUE THREAD

**Issue by seandavi** [metacran/metacranweb#5]
Clicking on package links or searching currently leads to "page not found".

**Comment by gaborcsardi** [comment]
Yes, it is a mockup only, sorry, it should be on the page:
https://twitter.com/GaborCsardi/status/582926430331383808

**Comment by seandavi** [comment]
Sorry!  I got this from another source without that detail.  I agree that this is a more "modern" approach to presenting R packages.  Can't wait to see it in action.

**Comment by gaborcsardi** [comment]
No worries. You can follow my twitter if you want to see the alpha version. Or just check it occasionally.
