### ISSUE TITLE
Think about including release notes from github

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/metacranweb#61]
Maybe.

**Comment by gaborcsardi** [comment]
We can get them from GH, in theory:
https://api.github.com/repos/hadley/testthat/releases/tags/v0.10.1

So if `URL` or `BugReports` refers to a GH repo, and we find a release with the same tag as the version (or maybe with a leading `v`), then we can use the release notes for that release.

**Comment by maelle** [comment]
Many issues here remind me of our (ongoing) efforts in [`codemetar`](https://github.com/ropensci/codemetar). Would it be feasible/smart for metacran to use `codemetar` to munge DESCRIPTION and such?

**Comment by gaborcsardi** [comment]
Actually, I don't want the release notes any more.  Already have README and NEWS, that's good.  Just  would need to make sure that they  actually  work well...
