### ISSUE TITLE
404s everywhere

### ISSUE THREAD

**Issue by barryrowlingson** [metacran/metacranweb#77]
As of yesterday I get 404 on these URLS:

http://www.r-pkg.org/
http://www.r-pkg.org/pkg/splancs
 and all other package pages I've tried...

but not:

http://www.r-pkg.org/search.html?q=splancs
http://www.r-pkg.org/about

'sup?

**Comment by gaborcsardi** [comment]
THanks for the heads up, the server that provides some docs stopped (again). 

Should be good now.

**Comment by doccstat** [comment]
It seems the website is giving 404s now...
