### ISSUE TITLE
Only first author of package mentioned on metacran (EOM)

### ISSUE THREAD

**Issue by helix123** [metacran/metacranweb#81]

**Comment by gaborcsardi** [comment]
You mean the maintainer? YEs, every package has one maintainer. But all authors are listed.

**Comment by helix123** [comment]
Oops, sorry. Was irritated by the "packagename by NAME" and have overlooked the authors field a bit down below. Maybe "by" sets a too strong hook in people's mind about authorship? However, I do not have a better suggestion.

**Comment by gaborcsardi** [comment]
I thought about that, too, but "maintained by" does not sound too good, and is longer. Anyway, if you have a better suggestion, please let me know.
