### ISSUE TITLE
CRAN date badge

### ISSUE THREAD

**Issue by brry** [metacran/metacranweb#86]
Feature request: Additionally to the **version** badges, could you also create **date** badges?
http://www.r-pkg.org/services#badges

Would it be hard to create bagdes from github DESCRIPTION files? Then in a github R package README.md, one could have both badges so users can quickly see how much the development version is ahead. See also my post at http://stackoverflow.com/q/40511046

**Comment by gaborcsardi** [comment]
It is actually very easy, and a good idea.

Would you have sg with a date on, or sg that says how long ago it was:

![](https://img.shields.io/badge/CRAN%20release-2016--11--14-green.svg)
![](https://img.shields.io/badge/CRAN%20release-3_months_ago-green.svg)

Would you color them? Or just plain green like the version badge?

**Comment by brry** [comment]
I like exact dates much better - but that's personal style, I guess. If it's not too hard, maybe you can even offer both...
I would go with the regular green...

**Comment by gaborcsardi** [comment]
How about just (optionally) adding the date to the version badge? Multiple badges called 'CRAN` might not look very good.

![](https://img.shields.io/badge/CRAN-1.0.1%20/%202016--11--14-brightgreen.svg)
![](https://img.shields.io/badge/CRAN-1.0.1%20 –%205%20months%20ago-brightgreen.svg)

OTOH this badge is quite crowded....

**Comment by brry** [comment]
I like the top one and think that's still OK with crowdedness.  
Maybe a comma would also look good:   1.0.1, 2016-03-28.

So would that work with the github version/date as well?

**Comment by gaborcsardi** [comment]
> Maybe a comma would also look good: 1.0.1, 2016-03-28.

![](https://img.shields.io/badge/CRAN-1.0.1%20/%202016--11--14-brightgreen.svg)
![](https://img.shields.io/badge/CRAN-1.0.1,%202016--11--14-brightgreen.svg)
![](https://img.shields.io/badge/CRAN-1.0.1%20–%202016--11--14-brightgreen.svg)
![](https://img.shields.io/badge/CRAN-1.0.1%20—%202016--11--14-brightgreen.svg)
![](https://img.shields.io/badge/CRAN-1.0.1%20@%202016--11--14-brightgreen.svg)

I think the en-dash is the best, no?

> So would that work with the github version/date as well?

No. Metacran has a CRAN database, no data about GitHub projects. It could query it on the fly (with some caching), but I am not sure if I want to do that.

**Comment by brry** [comment]
yes, with the long dash it looks really good. **Thanks so much!**
A bit sad that github would be more difficult, but it was worth a try...
BTW, now that I look at it: I find the less-intensive green in the first comment slightly more pleasant to look at than the bright green, but again, that's just personal opinion ;-)
