### ISSUE TITLE
Badge for CRAN package checks

### ISSUE THREAD

**Issue by gaborcsardi** [metacran/metacranweb#87]
Showing NOTE / WARNING/ ERROR.

**Comment by gaborcsardi** [comment]
![](https://img.shields.io/badge/CRAN-OK-green.svg)
![](https://img.shields.io/badge/CRAN-WARNING-orange.svg)
![](https://img.shields.io/badge/CRAN-ERROR-red.svg)

**Comment by maelle** [comment]
Cf @sckott's https://github.com/ropensci/cchecksapi 😸

**Comment by gaborcsardi** [comment]
Yeah, this is done by Scott.

**Comment by maelle** [comment]
Maybe there could be a link to the repo on METACRAN website even if it's not a METACRAN service? Under badges?
