### ISSUE TITLE
Properly display ORCIDs from author lists

### ISSUE THREAD

**Issue by nuest** [metacran/metacranweb#94]
CRAN now [displays a package author ORCID when provided](https://github.com/ropensci/codemetar#modifying-or-enriching-codemeta-metadata) in `person(..., comment = "https://orcid..")`:

![image](https://user-images.githubusercontent.com/1325054/33882599-e572356c-df38-11e7-94b1-37be40cdb674.png)

METACRAN does not, see for example `sf`: https://www.r-pkg.org/pkg/sf

![image](https://user-images.githubusercontent.com/1325054/33882247-c5c1a596-df37-11e7-9767-960d679dc7d0.png)

The guidelines how to embed the ORCIDs are at https://orcid.org/trademark-and-id-display-guidelines

@gaborcsardi PR welcome for this?

**Comment by gaborcsardi** [comment]
PR is welcome indeed, but I am afraid that it is harder than you think.

**Comment by nuest** [comment]
I have integrated the following design in #96

![image](https://user-images.githubusercontent.com/1325054/34209271-c36c5e8e-e591-11e7-95ba-3bedb8ac0a9b.png)


The template code is not good to read, because everything is one one line to avoid whitespace before the `,`. Is there a way to fix that?

We could also format authors as an HTML list.

**Comment by maelle** [comment]
I see in the PR that ORCID IDs are now displayed, this is awesome, :clap: to both of you!

I'll add a mention of this in my tech note https://github.com/ropensci/roweb2/pull/286 (and I also saw `pkgdown` displays them too btw)
